ezfund/urls.py
#coding:utf-8
"""ezfund URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
from django.views.static import serve
from django.contrib.auth import views as auth_views
from fund import views as fund_views

urlpatterns = [
    url(r'^$', fund_views.index, name='index'),
    url(r'^(?P<fund_id>[0-9]+)/$', fund_views.detail, name='detail'),
    url(r'^(?P<fund_id>[0-9]+)/approve', fund_views.approve, name='approve'),
    url(r'^(?P<fund_id>[0-9]+)/deny', fund_views.deny, name='deny'),
    url(r'^(?P<fund_id>[0-9]+)/upload_paycheck', fund_views.upload_paycheck, name='paycheck_upload'),
    url(r'^(?P<fund_id>[0-9]+)/paycheck_approve', fund_views.paycheck_approve, name='paycheck_approve'),
    url(r'^(?P<fund_id>[0-9]+)/paycheck_deny', fund_views.paycheck_deny, name='paycheck_deny'),
    url(r'^apply/$', fund_views.apply, name='apply'), 
    url(r'^admin/', admin.site.urls),
    url(r'^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^login/', auth_views.login, {'template_name': 'account/sign_in.html'},name='login'),
    url(r'logout_to_login/$', fund_views.logoutnlogin),
    url(r'^password_change/$', auth_views.password_change, {'template_name': 'account/password_change_form.html','post_change_redirect': 
'/?pwd=success'}, name='password_change'),
    url(r'sign_up/$', fund_views.SignUpView, name='sign_up'),
]
#password_change_done是修改成功后重定向的页面，如果需要可以设置

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

fund/urls.py
#coding:utf-8
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<fund_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<fund_id>[0-9]+)/approve', views.approve, name='approve'),
    url(r'^(?P<fund_id>[0-9]+)/deny', views.deny, name='deny'),
    url(r'^(?P<fund_id>[0-9]+)/upload_paycheck', views.upload_paycheck, name='paycheck_upload'),
    url(r'^(?P<fund_id>[0-9]+)/paycheck_approve', views.paycheck_approve, name='paycheck_approve'),
    url(r'^(?P<fund_id>[0-9]+)/paycheck_deny', views.paycheck_deny, name='paycheck_deny'),
    url(r'^apply/$', views.apply, name='apply'), 
]

fund/models.py
#coding:utf-8
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Fund(models.Model):
    class Meta:
        permissions = (
            ("apply_only", "可以提交申请"),
            ("student_approve", "学代通道"),
            ("teacher_approve", "老师通道"),
        )
    username = models.CharField(max_length=30)
    name = models.CharField(max_length=100)
    apply_date = models.DateTimeField('申请日期', default=timezone.now)
    activity_date = models.DateField('活动日期', default=timezone.now)#, default=timezone.now
    plan_file = models.FileField(upload_to='%y/%m/%d/plan_file')
    charger = models.CharField(max_length=20)
    charger_tel = models.CharField(max_length=30)
    activity_member = models.CharField(max_length=500)
    last_time = models.CharField(max_length=100)
    note = models.CharField(max_length=500)
    is_viewed_by_student = models.BooleanField(default=False)
    is_viewed_by_teacher = models.BooleanField(default=False)
    is_objected = models.BooleanField(default=False)
    paycheck_file = models.FileField(upload_to='%y/%m/%d/paycheck_file',blank = True)
    pc_stat = (
            ("not_uploaded", "等待提交结算表"),
            ("applied", "已提交结算表，等待审核"),
            ("stucon_approved", "学代已审核结算表"),
            ("stucon_disapproved", "结算表未通过学代审核"),
            ("teacher_approved", "老师已审核结算表"),
            ("teacher_disapproved", "结算表未通过老师审核"),
        )
    paycheck_status = models.CharField(max_length=30,choices=pc_stat,default="not_uploaded")

    def __str__(self):
        return self.name

    def fund_status(self):
        if not self.is_objected:
            if self.is_viewed_by_student:
                if self.is_viewed_by_teacher:
                    return u"申请成功"
                else:
                    return u"等待老师审批"
            else:
                return u"等待学代审批"
        else:
            if self.is_viewed_by_student:
                if self.is_viewed_by_teacher:
                    return u"团委书记否决"
                else:
                    return u"学代否决"
'''
    def paycheck_to_display(self):
        if self.paycheck_status != "not_uploaded":
            return True
        else:
            return False
'''

fund/forms.py
#coding:utf-8
from django import forms
from .models import Fund
from django.forms import ModelForm
from django.contrib.auth.models import User

class FundForm(ModelForm,forms.Form):
    class Meta:
        model = Fund
        fields = ['name','activity_date', 'plan_file', 'charger','charger_tel', 'activity_member', 'last_time', 'note']

class UserForm(forms.Form):  
    username = forms.CharField(label='用户名', max_length=30)
    email = forms.EmailField(label='邮箱地址', max_length=50)
    password = forms.CharField(label='密码', max_length=100,min_length=8,widget=forms.PasswordInput)

class PaycheckForm(forms.Form):
    paycheck_file = forms.FileField(label='上传文件')

    

fund/views.py
#coding:utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required

from .models import Fund

from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger
from django.core.paginator import EmptyPage

from operator import itemgetter, attrgetter

from .forms import FundForm, UserForm, PaycheckForm
from .check_per import detial_cp_decorator, apply_cp_decorator

from django.contrib.auth import views as auth_views
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User, Group



@login_required(login_url='/login/')
def index(request):
    now_user = request.user
    if now_user.has_perm(perm="fund.student_approve"):
        student_view = False
        stucon_view = True
        fund_objects = Fund.objects.all()
        paycheck_objects = Fund.objects.exclude(paycheck_status="not_uploaded")
    else:
        if now_user.has_perm(perm="fund.teacher_approve"):
            student_view = False
            stucon_view = False
            fund_objects = (Fund.objects.filter(is_objected=False, is_viewed_by_student=True) | Fund.objects.filter( is_viewed_by_teacher=True))
            paycheck_objects =((Fund.objects.exclude(paycheck_status="not_uploaded")).exclude(paycheck_status="applied")).exclude(paycheck_status="stucon_disapproved")
        else:
            if now_user.has_perm(perm="fund.apply_only"):
                student_view = True
                stucon_view = False
                fund_objects = Fund.objects.filter(username = now_user.username)
    fund_list = sorted(fund_objects, key=attrgetter('id'), reverse=True)
    paginator = Paginator(fund_list,10)
    page = request.GET.get('page')
    try:
        fund_list = paginator.page(page)
    except PageNotAnInteger:
        fund_list = paginator.page(1)
    except EmptyPage:
        fund_list = paginator.page(paginator.num_pages)
    if now_user.has_perm(perm="fund.student_approve") or now_user.has_perm(perm="fund.teacher_approve"):
        pc_list = sorted(paycheck_objects, key=attrgetter('id'), reverse=True)
        paginator4pc = Paginator(pc_list, 10)
        pc_page = request.GET.get('page')
        try:
            pc_list = paginator4pc.page(pc_page)
        except PageNotAnInteger:
            pc_list = paginator4pc.page(1)
        except EmptyPage:
            pc_list = paginator4pc.page(paginator4pc.num_pages)
        context = {
            'student_view': student_view,
            'stucon_view': stucon_view,
            'username': request.user.username,
            'fund_list': fund_list,
            'paycheck_list':pc_list,
        }
    else:
        context = {
            'student_view': student_view,
            'stucon_view': stucon_view,
            'username': request.user.username,
            'fund_list': fund_list,
        }
    return render(request, 'index.html', context)


@login_required(login_url='/login/')
@detial_cp_decorator
def detail(request, fund_id):
    now_user = request.user
    fund = get_object_or_404(Fund, pk=fund_id)
    if request.user.has_perm(perm="fund.apply_only"):
        work_btn = False
    else:
        work_btn = True
    if now_user.has_perm(perm="fund.student_approve"):
        stucon_view = True
    else:
        stucon_view = False
    if fund.paycheck_file:
        pc = True
    else:
        pc = False
    content = {
        'username': request.user.username,
        'fund': fund,
        'fund_stat': fund.fund_status(),
        'show_work_btn': work_btn,
        'stucon_view': stucon_view,
        'paycheck_uploaded': pc,
    }
    return render(request, 'detail.html', content)


@login_required(login_url='/login/')
@apply_cp_decorator
def apply(request):
    now_user = request.user
    if request.method == 'POST':
        form = FundForm(request.POST, request.FILES)
        if form.is_valid():
            apply_object = form.save()
            apply_object.username = now_user.username
            apply_object.save()
            success = True
            return render(request, 'apply.html', {'success':success})
        else:
            error = form.errors
            form = FundForm
            context = {
                'error':error,
                'form':form,
            }
            return render(request, 'apply.html', context)
    else:
        form = FundForm
    return render(request, 'apply.html', {'form':form})


@login_required(login_url='/login/')
@apply_cp_decorator
def upload_paycheck(request, fund_id):
    now_user = request.user
    app_fund = get_object_or_404(Fund, pk=fund_id)
    if request.method == 'POST':
        form = PaycheckForm(request.POST, request.FILES)
        if form.is_valid():
            app_fund.paycheck_file = request.FILES.get('paycheck_file')
            app_fund.paycheck_status = "applied"
            app_fund.save()
            success = True
            return render(request, 'upload_paycheck.html', {'success':success})
        else:
            error = form.errors
            form = PaycheckForm
            context = {
                'error':error,
                'form':form,
            }
            return render(request, 'upload_paycheck.html', context)
    else:
            form = PaycheckForm
            context = {
                'fund': app_fund,
                'form': form,
            }
    return render(request, 'upload_paycheck.html', context)

#预算表审核模块
@login_required(login_url='/login/')
def approve(request, fund_id):
    now_user = request.user
    if now_user.has_perm(perm="fund.student_approve"):
        app_fund = get_object_or_404(Fund, pk=fund_id)
        app_fund.is_viewed_by_student = True
        app_fund.save()
    else:
        if now_user.has_perm(perm="fund.teacher_approve"):
            app_fund = get_object_or_404(Fund, pk=fund_id)
            app_fund.is_viewed_by_teacher = True
            app_fund.save()
    return detail(request, fund_id)


@login_required(login_url='/login/')
def deny(request, fund_id):
    now_user = request.user
    if now_user.has_perm(perm="fund.student_approve"):
        app_fund = get_object_or_404(Fund, pk=fund_id)
        app_fund.is_viewed_by_student = True
        app_fund.is_objected = True
        app_fund.save()
    else:
        if now_user.has_perm(perm="fund.teacher_approve"):
            app_fund = get_object_or_404(Fund, pk=fund_id)
            app_fund.is_viewed_by_teacher = True
            app_fund.is_objected = True
            app_fund.save()
    return detail(request, fund_id)


#结算表审核模块
@login_required(login_url='/login/')
def paycheck_approve(request, fund_id):
    now_user = request.user
    if now_user.has_perm(perm="fund.student_approve"):
        app_fund = get_object_or_404(Fund, pk=fund_id)
        app_fund.paycheck_status = "stucon_approved"
        app_fund.save()
    else:
        if now_user.has_perm(perm="fund.teacher_approve"):
            app_fund = get_object_or_404(Fund, pk=fund_id)
            app_fund.paycheck_status = "teacher_approved"
            app_fund.save()
    return detail(request, fund_id)


@login_required(login_url='/login/')
def paycheck_deny(request, fund_id):
    now_user = request.user
    if now_user.has_perm(perm="fund.student_approve"):
        app_fund = get_object_or_404(Fund, pk=fund_id)
        app_fund.paycheck_status = "stucon_disapproved"
        app_fund.save()
    else:
        if now_user.has_perm(perm="fund.teacher_approve"):
            app_fund = get_object_or_404(Fund, pk=fund_id)
            app_fund.paycheck_status = "teacher_disapproved"
            app_fund.save()
    return detail(request, fund_id)

#未来添加双重密码验证注册
def SignUpView(request):
    if request.method == "POST":
        SignUpForm = UserForm(request.POST)
        if SignUpForm.is_valid():
            username = SignUpForm.cleaned_data['username']
            password = SignUpForm.cleaned_data['password']
            email = SignUpForm.cleaned_data['email']
            if User.objects.filter(username=username):
                SignUpForm = UserForm
                context = {
                    'SignUpForm': SignUpForm,
                    'reason': '用户名已存在，请选择其他用户名',
                    'username': request.user.username,
                    }
                return render(request, 'account/sign_up.html',context)
            else:
                user = User.objects.create_user(username, email, password)
                user.is_staff = True
                default_group = Group.objects.get(name='student union')
                default_group.user_set.add(user)
                user.save()
                login(request, authenticate(username=username, password=password))
                return HttpResponseRedirect('/')
        else:
            error = SignUpForm.errors
            SignUpForm = UserForm
            context = {
                'SignUpForm': SignUpForm,
                'reason': error,
                'username': request.user.username,
                }
            return render(request, 'account/sign_up.html', context)
    else:
        SignUpForm = UserForm
        context = {
            'SignUpForm': SignUpForm,
            'username': request.user.username,
        }
        return render(request, 'account/sign_up.html', context)

 
def logoutnlogin(request):
    """
    Logout n login back
    """
    return auth_views.logout_then_login(request,login_url='/login')

fund/templates/apply.html
{% extends "base.html" %}

{% block nav-title %}添加申请{% endblock %}


{% block main_container %}
    <div class="row">
        <div class="col s12">
            <div class="card-panel">
                <div class="card-content">
                    <a href="/" class="grey-text">申请列表</a>
                    <span> > </span>
                    <a href="apply/">添加申请</a>
                    <div class="right">
                    </div>
                </div>
            </div>
        </div>
    </div>

{% if error %}
<div class="container">
    <div class="row">
         <div class="col s12 m6 offset-m3">
            <div class="card-panel red lighten-2">
                <span class="white-text">申请失败：{{error}}</span>
            </div>
         </div>
    </div>
</div>
{% endif %}

<div class="row"> 
    <form method="post" enctype="multipart/form-data" class="col s12">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s6">
                {{ form.name }}
                <label for="activity_name">活动名称</label>
            </div>
            <div class="input-field col s6">
                {{ form.activity_date}}
                <label for="activity_date">活动时间</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                {{ form.charger}}
                <label for="activity_charger">负责人</label>
            </div>
            <div class="input-field col s6">
                {{ form.charger_tel}}
                <label for="activity_charger_tel">负责人联系电话</label>
            </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            {{ form.activity_member}}
            <label for="group_people">项目团队成员</label>
          </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                {{ form.last_time}}
                <label for="activity_length">持续时间</label>
            </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <textarea id="id_note" maxlength="500" name="note" type="text" required="" class="materialize-textarea"></textarea>
            <label for="note">备注</label>
          </div>
        </div>
        <div class="row">
            <div class="file-field input-field">
                <div class="btn">
                    <span>点击上传</span>
                    <input type="file" name="plan_file" required id="id_plan_file">
                  </div>
                  <div class="file-path-wrapper">
                    <input class="file-path validate" type="text" placeholder="活动策划书">
                  </div>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s4 offset-s5">
                <button data-target="modal1" class="btn waves-effect waves-light btn-large" type="submit" name="action">提交申请</button>
            </div>
        </div>
        </div>
    </form>
</div>

{% if success %}
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h4>提交成功！</h4>
      <p>您的申请会得到学代会和团委的审批，敬请留意！</p>
    </div>
    <div class="modal-footer">
      <a href="/" class="modal-action modal-close waves-effect waves-green btn-flat ">确定</a>
    </div>
  </div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script>
    $(document).ready(function(){
    // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
    $('.modal').modal();
    $('#modal1').modal('open');
  });
</script>
{% endif %}

{% endblock %}

fund/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="theme-color" content="#4db6ac">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block htmltitle %}深圳大学学生活动经费审批系统{% endblock %}</title>
    {% load static %}
  <!-- CSS  -->
    <link href="{% static 'css/iconfont.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/materialize.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection">
</head>
<body>
  <nav class="nav-extended teal lighten-2">
    <div class="nav-wrapper container">
      <a href="/" class="white-text">深圳大学学生活动经费审批系统</a>
      <a href="/" data-activates="mobile-demo" class="button-collapse"  id="nav_btn"><i class="iconfont icon-menu"></i></a>
      <ul class="right hide-on-med-and-down" id="nav_bar">
        <li><a href="#!">{{username}}</a></li>
        <li></i><a href="/password_change/">修改密码</a></li>
        <li><a href="/logout_to_login/">退出</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li>
          <div class="user-view" style="background-color:darkslategrey">
            <a><span class="white-text" style="font-size:1.5rem">{{username}}</span></a>
          </div>
        </li>
        <li><a class="waves-effect" href="/">首页</a></li>
        <li><div class="divider"></div></li>
        <li><a class="subheader">账户管理</a></li>
        <li><a class="waves-effect" href="/password_change/">修改密码</a></li>
        <li><div class="divider"></div></li>
        <li><a class="waves-effect" href="/logout_to_login/">退出</a></li>
      </ul>
    </div>
      <div class="nav-content container">

       <span class="nav-title">{% block nav-title %} 深圳大学学生活动经费审批系统 {% endblock %}</span>
       <a class="btn-floating btn-large halfway-fab waves-effect waves-light amber" href="apply/" id="add_button" style="display:none">
        <i class="iconfont" style="font-size:30px;text-align:top;">+</i>
      </a>
    </div>

  </nav>
  
  <div class="container">
    <br><br>
    {% block main_container %}
    {% endblock %}
    <br><br>
  </div>

 <footer class="page-footer grey lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="black-text">在使用中出现问题？</h5>
                <p class="black-text text-lighten-4">如果在使用过程中出现问题，请在学子天地公众号留言，或者在我们的值班时间（周一到周五第3~4节、第5~8节课）期间到西南综合楼112学子天地办公室告知我们的值班同学，我们将会尽快解决！</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="black-text">关注学子天地公众号</h5>
                <img src="{% static 'img/barcode.jpg' %}" height="200" width="200" >
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container black-text">
            © 2017 <a class="black-text text-lighten-4" href="http://stu.szu.edu.cn">学子天地</a>·技术部 版权所有
            </div>
          </div>
        </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/vue.js' %}"></script>
  <script src="{% static 'js/materialize.min.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>

  </body>
</html>

fund/templates/deny.html
<script type="text/javascript">
    alert("无权限访问，重定向至首页");
    window.location="/"
</script>

fund/templates/detail.html
{% extends "base.html" %}

{% block nav-title %}申请详情{% endblock %}


{% block main_container %}
    <div class="row">
        <div class="col s12">
            <div class="card-panel">
                <div class="card-content">
                    <a href="/" class="grey-text">申请列表</a>
                    <span> > </span>
                    <a href="/{{ fund.id }}/">详情</a>
                    <div class="right">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">活动名称：{{ fund.name }}</span>
                    <div class="container">
                        <table>
                            <tr>
                                <td>申请人:{{fund.username}}</td>
                            </tr>
                            <tr>
                              <td>当前状态:{{ fund_stat }}</td>
                              <td>活动时间：{{ fund.activity_date }}</td>
                            </tr>
                            <tr>
                                <td>策划书：<a href="/upload/{{ fund.plan_file }}">点击下载</a></td>
                                <td>持续时间：{{ fund.last_time }}</td>
                            </tr>
                            <tr>
                                <td>负责人：{{ fund.charger }}</td>
                                <td>负责人联系方式：{{ fund.charger_tel }}</td>
                            </tr>
                            <tr>
                                <td colspan="2">活动成员：{{ fund.activity_member }}</td>
                            </tr>
                            <tr>
                                <td colspan="2">备注：{{ fund.note }}</td>
                            </tr>
                            {% if fund.paycheck_file %}
                            <tr>
                                <td>结算表：<a href="/upload/{{ fund.paycheck_file }}">点击下载</a></td>
                                <td>
                                    结算表状态：
                                    {%ifequal fund.paycheck_status "applied" %}
                                    已提交结算表，等待审核
                                    {% endifequal %}
                                    {%ifequal fund.paycheck_status "stucon_approved" %}
                                    学代已审核结算表
                                    {% endifequal %}
                                    {%ifequal fund.paycheck_status "stucon_disapproved" %}
                                    结算表未通过学代审核
                                    {% endifequal %}
                                    {%ifequal fund.paycheck_status "teacher_approved" %}
                                    老师已审核结算表
                                    {% endifequal %}
                                    {%ifequal fund.paycheck_status "teacher_disapproved" %}
                                    结算表未通过老师审核
                                    {% endifequal %}
                                </td>
                            </tr>
                            {% endif %}
                        </table>
                        <br> </br>
                        <div class="row">
                                {% if show_work_btn %}
                                    {% if stucon_view %}
                                        {% if fund.is_objected %}
                                        <a class="red btn">已否决</a>
                                        {% elif fund.is_viewed_by_student %}
                                        <a class="green btn">已批准</a>
                                        {% else %}
                                        <a class="waves-effect green waves-light btn" href="/{{ fund.id }}/approve">批准</a>
                                        <a class="waves-effect red waves-light btn" href="/{{ fund.id }}/deny">否决</a>
                                        {% endif %}
                                    {% else %}
                                        {% if fund.is_objected %}
                                        <a class="red btn">已否决</a>
                                        {% elif fund.is_viewed_by_teacher and fund.is_viewed_by_student %}
                                        <a class="green btn">已批准</a>
                                        {% else %}
                                        <a class="waves-effect green waves-light btn" href="/{{ fund.id }}/approve">批准</a>
                                        <a class="waves-effect red waves-light btn" href="/{{ fund.id }}/deny">否决</a>
                                        {% endif %}
                                    {% endif %}
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

fund/templates/upload_paycheck.html
{% extends "base.html" %}

{% block nav-title %}上传 {{ fund.name }} 的结算表{% endblock %}


{% block main_container %}

{% if error %}
<div class="container">
    <div class="row">
         <div class="col s12 m6 offset-m3">
            <div class="card-panel red lighten-2">
                <span class="white-text">上传失败：{{error}}</span>
            </div>
         </div>
    </div>
</div>
{% endif %}

<div class="row"> 
    <form method="post" enctype="multipart/form-data" class="col s12">
        {% csrf_token %}
        <div class="row">
        <div class="col s12">
            <div class="card-panel">
                <div class="card-content">
                    <div class="row">
                        <div class="input-field col s12">
                          <span>上传结算表:{{ form.paycheck_file }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <div class="row">
            <div class="input-field col s4 offset-s5">
                <button data-target="modal1" class="btn waves-effect waves-light btn-large" type="submit" name="action">上传结算表</button>
            </div>
        </div>
    </form>
</div>

{% if success %}
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h4>上传成功！</h4>
      <p>请耐心等待学代会和团委的审批！</p>
    </div>
    <div class="modal-footer">
      <a href="/" class="modal-action modal-close waves-effect waves-green btn-flat ">确定</a>
    </div>
  </div>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script>
    $(document).ready(function(){
    // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
    $('.modal').modal();
    $('#modal1').modal('open');
  });
</script>
{% endif %}

{% endblock %}